### ISSUE TITLE
How to create WIF for LTC, LTC test

### ISSUE THREAD

**Issue by bachlongkocanh** [bitcoinjs/wif#18]
I create WIF from hex.
```js
 const WIFKEY = require('wif');
 let decodeWIF = {
        version: 176,
        privateKey: Buffer.from(privateKey, 'hex'),
        compressed: true
    }
 let WIF =  WIFKEY.encode(decodeWIF);
```
but WIF return WIF format in bitcoin. Start with `K` or `L`.
How to create wif for LTC???

**Comment by junderw** [comment]
Change the version to match LTC.

There's a package called coininfo with all that info.
