### ISSUE TITLE
version in decode

### ISSUE THREAD

**Issue by fanatid** [bitcoinjs/wif#3]
Why `version` for `decode` function is necessary? Of course if you use this package for wallet -- version check is very helpful, but what if you just need extract private key?

**Comment by dcousens** [comment]
@fanatid I'm open to this,  this module was initially extracted to match how it was being used.

If `version !== undefined` then, and only then enforce the version?

**Comment by dcousens** [comment]
Would be a breaking change, but, thats OK.

**Comment by fanatid** [comment]
We can swap arguments order -- `decode(string, version)` in this case 2.0.0 required.
Or write something like this for back compatibility:
```js
function decodeRaw(version, buffer) {
  if (arguments.length === 1) {
    buffer = version
    version = undefined
  }

  if (version !== undefined && buffer[0] !== version) {
    throw new Error('Invalid network version')
  }

  ...
}

function decode(version, string) {
  if (arguments.length === 1) {
    string = version
    version = undefined
  }

  return decodeRaw(version, bs58check.decode(string))
}
```

**Comment by dcousens** [comment]
I've already had several people tell me they wanted the other argument order anyway,  including in https://github.com/bitcoinjs/bitcoinjs-lib/pull/446#discussion_r37706221.

I'm sure that will be fine.

**Comment by fanatid** [comment]
ok, so can I create PR with changing arguments order and bumping version to 2.0.0?
btw, whats mean `d` in `decodeRaw` object? decoded?

**Comment by dcousens** [comment]
`d` is for the private key,  it is a commonly used variable name for private keys in ECDSA in general,  like `Q` for a public key, and `r` and `s` for the signature components.
I preferred it over `privateKey` due to the nature of the return result being a `BigInteger`, not a `Buffer`.

**Comment by dcousens** [comment]
> I preferred it over privateKey due to the nature of the return result being a BigInteger, not a Buffer.

Well, its result **used** to be a `BigInteger`.
