### ISSUE TITLE
'd' is meaningless to those who aren't familiar with ECDSA

### ISSUE THREAD

**Issue by jprichardson** [bitcoinjs/wif#5]
I've noticed it consistently `d`, `Q`, etc are used throughout bitcoinjs-lib. Internally, I think that's fine. As for an external interface for API consumers, do you think there could be friendlier names chosen? `privKey`, `privateKey`?

I'll volunteer to help you clean up the docs for this module too if you'd like.

**Comment by dcousens** [comment]
True.

And I think `privateKey` is OK in this case, since its not a `bigi`, which is where I've been consistently been using it for identifying between when its being used for EC or just storage.

**Comment by dcousens** [comment]
Shall we make the change and bump it 2.0.0?

**Comment by fanatid** [comment]
I already made this (except `buffer` instead `privateKey` now), furthermore PR #4 solves #1 and #3

**Comment by dcousens** [comment]
I'm happy either way, sorry I forgot that PR @fanatid

**Comment by dcousens** [comment]
Merged #4,  which changed this to `privateKey`, will release as `2.0.0` at some point soon.
