### ISSUE TITLE
How to create WIF for BTC Testnet 

### ISSUE THREAD

**Issue by VishalDalve** [bitcoinjs/wif#9]
Creating WIF on mainnet working perfectly, Nice work, thanks.
How can I get WIF for BTC Testnet Address?

**Comment by vladikus10** [comment]
Shouldn't it be enough to specify the version `0xef` instead of `0x80` (`128`) ?

**Comment by rahulEth** [comment]
just covert  hexadecimal (0xef) to decimal (239) for testnet  everything would work fine

**Comment by rahulEth** [comment]
var privKey = new Buffer(privateKey, 'hex');
var wifKey = wif.encode(239, privKey, true);//for testnet 0xEF, for mainnet 0x80

**Comment by ekkis** [comment]
some mnemonics would be good then

**Comment by ekkis** [comment]
I've added a PR to document that.  if acceptable I'm happy to enhance the module with the above

**Comment by junderw** [comment]
This has been documented thanks to ekkis.

tbh the wif library is not the place to include network info, since many other coins use wif.

coininfo library and bitcoinjs itself contain network info for bitcoin.
